### ISSUE TITLE
你好，我看你代码里有标签是anger,但是CASME2是没有这个标签的。

### ISSUE THREAD

**Issue by weijieZhu0803** [Shao-kun-Zhang/micro_expression_pytorch#5]
regression和others标签你是怎么处理的

**Comment by zskadazhang** [comment]
你好，很抱歉回复这么晚，anger标签是有的呀，

**Comment by zskadazhang** [comment]
你可以再具体看看那个数据集

**Comment by weijieZhu0803** [comment]
我的数据集只有happiness、others、disgust、repression、fear、surprise、sadness，这七种。而且申请的数据库也直接有cropped，为什么您用视频来做，您这code有写进论文嘛，还是只是一个demo

**Comment by zskadazhang** [comment]
only a demo for video classification



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
19/07/02
上午09:33:43

weijieZhu0803 <notifications@github.com> 于2019年7月1日周一 上午9:45写道：

**Comment by weijieZhu0803** [comment]
请问您用的什么配置的工作站训练的，我把你的视频输入改成直接20帧的图片输入，用batch为2训练，1080ti显存溢出

**Comment by zskadazhang** [comment]
GTX 960m,如果按照我代码的配置，你这样的配置训练应该是可以的呀，你可以试试将视频帧进行一个压缩



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
19/07/08
上午08:22:56

weijieZhu0803 <notifications@github.com> 于2019年7月7日周日 下午3:23写道：

**Comment by weijieZhu0803** [comment]
您这个跑完精度大概多少，我能加您qq或者微信交流吗
